# Generated by Django 4.0.2 on 2022-07-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(default='', max_length=15)),
                ('long_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
